version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ./:/var/www

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./docker/workspace
        args:
          - APP_ENV=${APP_ENV}
      volumes_from:
        - applications
      extra_hosts:
          - "dockerhost:${DOCKER_HOST_IP}"
      tty: true

### Node Container ##########################################

    node:
      build:
        context: ./docker/node
      volumes_from:
        - applications
      tty: true

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./docker/php-fpm
        args:
          - APP_ENV=${APP_ENV}
      volumes_from:
        - applications
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./docker/nginx
        args:
          - PHP_UPSTREAM=php-fpm
      volumes_from:
          - applications
      volumes:
          - ./logs:/var/log/nginx
          - ./docker/nginx/sites:/etc/nginx/sites-available
      ports:
          - "80:80"
      depends_on:
          - php-fpm

### Redis Container #########################################

    redis:
      build: ./docker/redis
      volumes:
        - redis:/data
      ports:
        - "6379:6379"

### Scrapy Container #########################################

    scrapy:
      build: ./docker/scrapy
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      depends_on:
        - mongo
      tty: true

### MongoDB Container #######################################

    mongo:
      build: ./docker/mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo:/data/db

### MySQL Container #########################################

    mysql:
      build:
        context: ./docker/mysql
        args:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - "3306:3306"

### phpMyAdmin Container ####################################

    phpmyadmin:
      build: ./docker/phpmyadmin
      environment:
        - PMA_ARBITRARY=0
        - PMA_HOST=${DOCKER_HOST_IP}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
        - "${PMA_PORT}:80"
      depends_on:
        - "${PMA_DB_ENGINE}"

### Volumes Setup ###########################################

volumes:
  redis:
    driver: "local"
  mongo:
    driver: "local"
  mysql:
    driver: "local"
  phpmyadmin:
    driver: "local"

