version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ./:/var/www

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./docker/workspace
        args:
          - APP_ENV=${APP_ENV}
      volumes_from:
        - applications
      extra_hosts:
          - "dockerhost:${DOCKER_HOST_IP}"
      tty: true

### Node Container ##########################################

    node:
      build:
        context: ./docker/node
      volumes_from:
        - applications
      tty: true

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./docker/php-fpm
        args:
          - APP_ENV=${APP_ENV}
      volumes_from:
        - applications
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
