version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ./:/var/www

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./docker/workspace
        args:
          - APP_ENV=${APP_ENV}
      volumes_from:
        - applications
      extra_hosts:
          - "dockerhost:${DOCKER_HOST_IP}"
      tty: true

### Node Container ###########################

    node:
      build:
        context: ./node
      volumes_from:
        - applications
      tty: true
